FROM nginx:alpine

# Copia o arquivo do Windows diretamente para o motor mestre do NGINX
COPY nginx.conf /etc/nginx/nginx.conf

# A linha mágica: converte as quebras de linha e limpa a sujeira do Windows (CRLF para LF)
RUN sed -i 's/\r$//' /etc/nginx/nginx.conf