global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'projeto-korp-api'
    static_configs:
      # Aponta para o nome do container da API na rede interna do Docker
      - targets: ['api:8080']